### ISSUE TITLE
Add instructions for changes in Execution policy

### ISSUE THREAD

**Issue by andycsoto** [KuryKat/LeagueOfLanguages#1]
### Describe your suggestion

Windows 11 Home has ExecutionPolicy set to Restricted.
Regular users experience a blink of PowerShell when clicking the script for execution.

I suggest adding a paragraph that includes that they should execute as an Admin in Powershell `Set-ExecutionPolicy RemoteSigned` so that the script works as intended

### Why would you like this added/changed?

To allow regular users to use the script seamlessly

**Comment by KuryKat** [comment]
Thank you very much for your suggestion! We do include a piece of information about the ExecutionPolicy in the [Troubleshooting Wiki](../wiki/Troubleshooting-2.0.0) but if you think we should move this somewhere else or add it somewhere else let me know!

Also let me know if you think the instructions are unclear!

**Comment by KuryKat** [comment]
Also, Thank You for letting me know of this Windows 11 change, before it was default at RemoteSigned on Windows 10
