### ISSUE TITLE
Shortcut automatically changes to "regular" shortcut

### ISSUE THREAD

**Issue by Zero8000** [KuryKat/LeagueOfLanguages#2]
### Version

2.0.1

### Describe your issue.

Generally speaking the shortcut creation goes fine, but after opening it the first time the shortcut automatically changes to the one used automatically by Riot's client, with the launch-product line to open League from the Riot launcher. I have to re-run the script after deleting the first shortcut. Even still, whenever I open, I often have to attempt to open the game three times or so before it finally opens as the Riot launcher comes up, then it shows me League in the launcher, and then the game opens in my desired language.

### Have you modified the script?

Yes.

### User Modifications

Shortcut location changed from the original to where I have the game installed (E: drive.)

### Discord Username

Zero8000 (zero8000)

**Comment by KuryKat** [comment]
Thank you for your issue report! I will look into it to see if it can fixed on our side.

However I should inform you, the LeagueClient shortcut gets automatically updated to the RiotClient location once you execute it, that is Riot's intended design. Sadly there is not much I can do to mitigate that effect. The only thing you can really do is run the script again every time you need to change the language again.

About the second issue: have you tried making sure that you closed the Riot Launcher in the system tray to assure that the game is fully closed before trying to run the script again?

From my experience I noticed that the Riot Launcher will always try to ensure your specific Region's Language, probably an intended design, so the way I found to mitigate this is to completely close the Launcher before opening the game again with a new Language.

To achieve this you first have to open your Riot Client, then click on the "User" 

![image](https://github.com/KuryKat/LeagueOfLanguages/assets/57152799/5f83acde-00b8-42ef-abf6-322f42cf11e1)

Then click on Settings

![image](https://github.com/KuryKat/LeagueOfLanguages/assets/57152799/a081ea53-55d3-4ea2-a64f-97984f3a8cf9)

In there make sure you **don't** have the Riot Client to run on startup, and also set the Close Window behavior to Exit the Application.

![image](https://github.com/KuryKat/LeagueOfLanguages/assets/57152799/9d0ae8ce-6e48-4b7e-bbc5-d7a13700c97e)

After that, close the Riot Client, make sure to close it in the system tray as well if is still there:

![image](https://github.com/KuryKat/LeagueOfLanguages/assets/57152799/826de3ce-3ee2-4d3c-b5aa-c9171ad5a911)

Then trying running the Script and executing the new LeagueClient shortcut, you can delete the created shortcut after you open it, as it will get updated to the new location anyways 😅😅

![image](https://github.com/KuryKat/LeagueOfLanguages/assets/57152799/adb5138f-7a27-4bd1-8e02-55b7ab806734)

![image](https://github.com/KuryKat/LeagueOfLanguages/assets/57152799/959bd4aa-c605-4150-a9b5-9649bedb3cde)

Then whenever you need to change the language again you just need to run the script again, ensure your game is fully closed, and run the new shortcut!

Hope this helps! Thank you for your time and your report!

**Comment by KuryKat** [comment]
Let me know if you have any other concerns or comments, I will close this issue for now as it isn't something I can actively mitigate, if you have any more information that can be useful for us to know how to change this behavior, let us know!
